name: Daily Check Deadlines

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-deadlines:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Function
        run: |
          curl -X POST "https://stately-sundae-b61659.netlify.app/.netlify/functions/check-deadlines" \
          -H "Content-Type: application/json"
